GET {{host}}/api/user
Accept: */*
Cache-Control: no-cache
Content-Type: application/json
Authorization: {{token}}



###
POST {{host}}/api/authorizations
Accept: */*
Cache-Control: no-cache
Accept: application/json
Content-Type: application/json

{"code":"043WDS8i072Khu1R3I9i0alI8i0WDS8o"}

> {% client.global.set("token", response.body.data.access_token); %}
###
GET {{host}}/api/authorizations
Accept: */*
Cache-Control: no-cache
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

###
GET {{host}}/api/coupon/latest
Accept: */*
Cache-Control: no-cache
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

###
