GET http://life.test/api/user
Accept: */*
Cache-Control: no-cache
Accept: application/json
Content-Type: application/json
Authorization: {{token}}




###
POST http://life.test/api/like/store/1
Accept: */*
Cache-Control: no-cache
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

###
POST {{host}}/api/authorizations
Accept: */*
Cache-Control: no-cache
Accept: application/json
Content-Type: application/json

{"code":"023VmlDV1Cvwt11cMyAV1EojDV1VmlDC"}

###
GET {{host}}/api/coupon/recommend
Accept: */*
Cache-Control: no-cache
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

###
GET {{host}}/api/coupon/latest
Accept: */*
Cache-Control: no-cache
Accept: application/json
Content-Type: application/json
Authorization: {{token}}

###
